# Apache asosidagi Docker imijidan foydalanamiz
FROM httpd:2.4

# HTML faylingizni Apache root papkasiga nusxalash
COPY ./index.html /usr/local/apache2/htdocs/

# Apache serverni ishga tushirish (default CMD)
