name: CI/CD for Docker Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repositoryni klonlash
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installing Docker
        run: sudo apt install docker docker-compose

      # 2. Docker Compose bilan image yaratish
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      # 3. Docker Hub yoki GitHub Container Registry uchun login qilish
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Docker image’larni Docker Hub’ga push qilish
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 1. SSH orqali serverga ulanish va Docker Compose orqali ishga tushirish
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/devme.uz/dev/docker
            docker-compose pull
            docker-compose up -d
